YTTask_Backend/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("", home, name="landingpage"),
    path("createsuperuser/", create_superuser),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from .views import create_yttasker, login_yttasker, logout_yttasker
app_name = "accounts"
urlpatterns = [
   path('create_yttasker/', create_yttasker, name="create_yttasker"),
   path('login_yttasker/', login_yttasker, name="login_yttasker"),
   path('logout_yttasker/', logout_yttasker, name="logout_yttasker")

]

dashboard/urls.py
from django.urls import path
from .views import *
app_name = "dashboard"
urlpatterns = [
   path('', dashboard, name="dashboard"),
   path('notification/', notification, name="notification"),
   path('user_profile/', user_profile, name="user_profile"),
   path('user_profile/update/<int:id>/', update_profile, name="update_profile"),
   path('check_complete/<str:task_title>/<int:id>/', check_complete, name="check_complete")
   
]

dashboard/models.py
from django.db import models
from accounts.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=500)
    description = models.TextField()
    prompt = models.CharField(max_length=500)
    point = models.FloatField()
    secret_code = models.CharField(max_length=50)

    class Meta:
        db_table = 'dashboard_task'






    def __str__(self):
        return self.title

class YTTasker_task(models.Model):
    tasker = models.ForeignKey('accounts.User',  on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)

   
    def __str__(self):
        return f'{self.tasker} - {self.task}'

    @receiver(post_save, sender=Task)
    def create_yttasker_task(sender, instance, created, **kwargs):
        users = User.objects.all()
        if created:
            for user in users:
                YTTasker_task.objects.using('second_db').create(tasker=user, task=instance)

class Notification(models.Model):
    info = models.CharField(max_length=500)
    pub_date = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.info
    

class FAQ(models.Model):
    question = models.CharField(max_length=500)
    answer = models.TextField()

    def __str__(self):
        return self.question

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from accounts.models import Profile, User
from dashboard.models import Notification
from accounts.forms import ProfileForm
# Create your views here.
@login_required(login_url="accounts:login_yttasker")
def dashboard(request):
    tasks = Task.objects.all()
    yttasker_task = YTTasker_task.objects.all()

    new_yttasker_task = YTTasker_task.objects.filter(tasker=request.user, completed=True)
    point_sum = 0
    for task in new_yttasker_task:
        point_sum += task.task.point
    
    return render(request, "dashboard/dashboard.html", {"tasks": tasks, "yttasker_tasks": yttasker_task, "point_sum": point_sum})

@login_required(login_url="accounts:login_yttasker")
def notification(request):
    new_yttasker_task = YTTasker_task.objects.filter(tasker=request.user, completed=True)
    point_sum = 0
    for task in new_yttasker_task:
        point_sum += task.task.point
    notifications = Notification.objects.all()
    faqs = FAQ.objects.all()
    return render(request, "dashboard/notification.html", {"notifications": notifications, "faqs": faqs, "point_sum": point_sum})

@login_required(login_url="accounts:login_yttasker")
def user_profile(request):
    if request.user.is_staff:

        return render(request, "dashboard/user_profile.html")
    new_yttasker_task = YTTasker_task.objects.filter(tasker=request.user, completed=True)
    point_sum = 0
    for task in new_yttasker_task:
        point_sum += task.task.point
    profile = Profile.objects.get(yttasker__email=request.user)
    return render(request, "dashboard/user_profile.html", {"yttasker_profile": profile,"point_sum": point_sum})
@login_required(login_url="accounts:login_yttasker")
def check_complete(request, task_title, id):
    yttasker_task = YTTasker_task.objects.filter(task=id, tasker=request.user).first()
    if request.method == "POST":
        code = request.POST.get("check_number")
        if code == yttasker_task.task.secret_code:
            yttasker_task.completed = True
            yttasker_task.save()
     
    
    return redirect("dashboard:dashboard")

def update_profile(request, id):
    form = ProfileForm()
    if request.method == 'POST':
        profile = Profile.objects.get(yttasker__email=request.user)
       
        profile.username = request.POST.get("username")

        profile.email = request.POST.get('email')
        profile.momo_number = request.POST.get("momo_number")
        profile.password = request.POST.get("password")
        profile.phonenumber = request.POST.get("phonenumber")
        profile.save()
        return redirect("dashboard:user_profile")
    return render(request, "dashboard/user_profile.html", {"form": form})

dashboard/templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&family=Poppins&family=Open+Sans&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'dashboard/style.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/base.css' %}">
    {% block custom-css %}
      
    {% endblock custom-css %}
    <title>YTTasks</title>
</head>
<body>
    <nav class="navbar">
        
        <div class="nav-logo">
            <img src=" {% static 'images/logo.png' %}" alt="">
            <span><a href="{% url 'dashboard:dashboard' %}">YTTasks.gh</a></span>
        </div>

        <div class="nav-action">
            {% block payout %}
              
            {% endblock payout %}
            <a href="{% url 'accounts:logout_yttasker' %}" class="btn">Logout</a>
            
        </div>
         <!-- Nav-trigger -->
         <div class="nav-trigger" id="nav-trigger">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </nav>
    <!-- Sidebar -->
    {% block sidebar %}
      
    {% endblock sidebar %}
    
       
    {% block content %}
        
    {% endblock content %}
   


    <footer class="footer">
        <span>Copyright &copy YTTasks.com, 2023</span>
        <small>YTTasks</small>
    </footer>



    <script>
        //Sidebar
        const navTrigger = document.getElementById("nav-trigger")
        const sidebar = document.getElementById("sidebar")
        navTrigger.addEventListener("click", ()=>{
            navTrigger.classList.toggle("active")
            sidebar.classList.toggle("active")
        })


        
        
       
    </script>
</body>
</html>

dashboard/templates/dashboard/dashboard.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block custom-css %}
<link rel="stylesheet" href="{% static 'dashboard/dashboard.css' %}">
{% endblock custom-css %}
{% block payout %}
<div class="payout">
    <small><span>${{point_sum |floatformat:"3"}}</span></small>
</div>
{% endblock payout %}
{% block sidebar %}
<div class="sidebar" id="sidebar">
    <div class="content">
        <div class="navigation">
            <li class="active"><a href="#"><i class="bx bx-briefcase"></i>Todays Task</a></li>
            <li><a href="{% url 'dashboard:notification' %}"><i class="bx bx-notification"></i>Notification</a></li>
            <li><a href="{% url 'dashboard:user_profile' %}"><i class="bx bx-user"></i>User Profile</a></li>
        </div>
        <div class="payout">
            <small>Payout = <span>${{point_sum |floatformat:"3"}}</span></small>
        </div>
        <li><a href="{% url 'accounts:logout_yttasker' %}">Logout</a></li>
        
    </div>
</div>
{% endblock sidebar %}
{% block content %}
<div class="main">
   
    <div class="sidemenu">
        <li class="active"><a href="#"><i class="bx bx-briefcase"></i>Todays Task</a></li>
        <li><a href="{% url 'dashboard:notification' %}"><i class="bx bx-notification"></i>Notification</a></li>
        <li><a href="{% url 'dashboard:user_profile' %}"><i class="bx bx-user"></i>User Profile</a></li>
        <div class="extra-menu">
            
            <small><b>{{request.user.email}}</b></small>
            <li><a href="{% url 'accounts:logout_yttasker' %}">Logout</a></li>
        </div>
    </div>
 
    <div class="main-content">
        <div class="urgent_message">
            <span><b>Work begins on 25th August, 2023</b></span>
            <small>Click <a href="https://t.me/YTTaskers"> this link </a>for next steps</small>
        </div>
        <span>Copy and paste these links into the decryptr engine</span>
        <div class="card-container">
            {% for task in tasks  %}
            <div class="card">
                <div class="card-num">
                    <small>{{forloop.counter}}</small>
                </div>
                <div class="card-content">
                    <div class="first">
                        <input type="text" value="{{task.prompt}}" id="prompt_{{forloop.counter}}" placeholder="{{task.prompt}}">
                        <div class="points">
                            <b>${{task.point}}</b>
                        </div>
                        <button href="{{task.link}}" class="btn prompt-btn" onclick="copyPrompt('prompt_{{forloop.counter}}'); return false;">Copy Prompt</button>
        
                    </div>
                    <div class="action">
                        
                        {% for yttasker_task in yttasker_tasks %}
                            {% if yttasker_task.task.title == task.title %}
                                {% if yttasker_task.completed is True and yttasker_task.tasker == request.user %}
                                <div class="completed">
                                    <small>Completed</small>
                                    <i class="bx bx-check-circle"></i>
                                </div>
                                {% else %}
                                
                                    {% if yttasker_task.completed is False and yttasker_task.tasker == request.user %}
                                    
                                    <form action="{% url 'dashboard:check_complete' task.title task.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="number" placeholder="Enter encoding key" name="check_number" id="">
                                        <input class="hidden_task" type="text" name="task_title" id="" value="{{task.title}}">
                                        <button href="#" type="submit" class="btn">verfiy code</button>
                                    </form>
                                    {% endif %}
                                {% endif %}
                                
                            {% endif %}
                        {% endfor %}
                       
                    </div>
                </div>
            </div>
            {% endfor %}
            
        </div>
       
    </div>
</div>

<script>
  
 

  function copyPrompt(promptId) {
    var promptInput = document.getElementById(promptId);
        var promptContent = promptInput.value;

        // Create a temporary input element to copy the prompt content
        var tempInput = document.createElement("input");
        tempInput.setAttribute("value", promptContent);
        document.body.appendChild(tempInput);

        // Select the content of the temporary input element
        tempInput.select();
        tempInput.setSelectionRange(0, promptContent.length);

        // Copy the selected content to the clipboard
        document.execCommand("copy");

        // Remove the temporary input element
        document.body.removeChild(tempInput);

        // Update the button text to show "Copied"
        var buttons = document.getElementsByClassName("prompt-btn");
        for (var i = 0; i < buttons.length; i++) {
            if (buttons[i] === event.target) {
                buttons[i].innerHTML = "Copied";
            } else {
                buttons[i].innerHTML = "Copy Prompt";
            }
        }
}
        const content_stretch = document.querySelectorAll("#content_description")
        for(const stretch of content_stretch){
            stretch.addEventListener("click", ()=>{
                if(stretch.classList.contains("stretch")){
                    stretch.innerHTML="Content Description <i class='bx bx-chevron-down'></i>"
                    stretch.classList.remove("stretch");
                }else{
                    stretch.innerHTML="Content Description <i class='bx bx-chevron-up'></i>"
                    stretch.classList.add("stretch");
                }
                
                
                
                const parentDiv = stretch.closest(".description")
                const cardDiv = stretch.closest(".card")
                cardDiv.classList.toggle("expand")
                stretch.classList.toggle("expand")
                const content_paragraph = parentDiv.querySelector("p")
                if(content_paragraph){

                    content_paragraph.classList.toggle("expand")
                }
            })
            
        }

    
</script>
{% endblock content %}
   

dashboard/templates/dashboard/notification.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block custom-css %}
<link rel="stylesheet" href="{% static 'dashboard/notification.css' %}">
{% endblock custom-css %}
{% block payout %}
<div class="payout">
    <small>Payout = <span>${{point_sum |floatformat:"3"}}</span></small>
</div>
{% endblock payout %}
{% block sidebar %}
<div class="sidebar" id="sidebar">
    <div class="content">
        <div class="navigation">
            <li><a href="{% url 'dashboard:dashboard' %}"><i class="bx bx-briefcase"></i>Todays Task</a></li>
            <li class="active"><a href="#"><i class="bx bx-notification"></i>Notification</a></li>
            <li><a href="{% url 'dashboard:user_profile' %}"><i class="bx bx-user"></i>User Profile</a></li>
        </div>
        <div class="payout">
            <small>Payout = <span>${{point_sum |floatformat:"3"}}</span></small>
        </div>
        <li><a href="{% url 'accounts:logout_yttasker' %}">Logout</a></li>
        
    </div>
</div>
{% endblock sidebar %}
{% block content %}
<div class="main">
    <div class="sidemenu">
        <li><a href="{% url 'dashboard:dashboard' %}"><i class="bx bx-briefcase"></i>Todays Task</a></li>
        <li class="active"><a href="#"><i class="bx bx-notification"></i>Notification</a></li>
        <li><a href="{% url 'dashboard:user_profile' %}"><i class="bx bx-user"></i>User Profile</a></li>
        <div class="extra-menu">
            <small><b>{{request.user.email}}</b></small>
            <li><a href="{% url 'accounts:logout_yttasker' %}">Logout</a></li>
        </div>
    </div>

    <div class="main-content">
                
        <div class="notification-container">
            <div class="noti-card-container">
                <h3>Notifications</h3>
                <div class="noti-card-list">
                    {% for notification in notifications  %}
                       <div class="noti-card">
                        
                        <div class="info">
                            <p>Info: <small>{{notification.pub_date}}</small></p>
                            <small>{{notification.info}}</small>
                        </div>
                       
                    </div>
                    {% endfor %}
                    
                    <!-- <div class="noti-card">
                        <div class="date">
                            <p>Date:</p>
                            <small>21/09/2023</small>
                        </div>
                        <div class="info">
                            <p>Info:</p>
                            <small>Payment of 14.59 cedis has been billed to your momo wallet</small>
                        </div>
                        <div class="amount">
                            <p>Amount:</p>
                            <small><b>14.59 cedis</b></small>
                        </div>
                        <div class="status">
                            <p>Status:</p>
                            <small><b>Paid</b></small>
                        </div>
                    </div> -->
                </div>
            </div>
            <div class="faqs-container">
                <h3>FAQs</h3>
                <div class="faqs-list">
                    {% for faq in faqs  %}
                        <div class="faqs">
                            <span class="question" id="question">{{faq.question}}</span>
                            <p class="content">{{faq.answer}}</p>
                        </div>
                    {% endfor %}
                    
                   
                </div>
            </div>
        </div>
    </div>
</div>
<script>
     //Notification js
     const content_stretch = document.querySelectorAll("#question")
        for(const stretch of content_stretch){
            stretch.addEventListener("click", ()=>{
                if(stretch.classList.contains("stretch")){
                   
                    stretch.classList.remove("stretch");
                }else{
                   
                    stretch.classList.add("stretch");
                }
                
                
                
                const parentDiv = stretch.closest(".faqs")
               
                parentDiv.classList.toggle("expand")
                const content_paragraph = parentDiv.querySelector("p")
                if(content_paragraph){

                    content_paragraph.classList.toggle("expand")
                }
            })
            
        }
</script>
{% endblock content %}
   


       

    </script>
</body>
</html>

dashboard/templates/dashboard/user_profile.html
{% extends "dashboard/base.html" %}
{% load static %}
{% block custom-css %}
  <link rel="stylesheet" href="{% static 'dashboard/user_profile.css' %}">
{% endblock custom-css %}
{% block payout %}
<div class="payout">
    <small><span>${{point_sum |floatformat:"3"}}</span></small>
</div>
{% endblock payout %}
{% block sidebar %}
<div class="sidebar" id="sidebar">
    <div class="content">
        <div class="navigation">
            <li><a href="{% url 'dashboard:dashboard' %}"><i class="bx bx-briefcase"></i>Todays Task</a></li>
            <li><a href="{% url 'dashboard:notification' %}"><i class="bx bx-notification"></i>Notification</a></li>
            <li class="active"><a href="#"><i class="bx bx-user"></i>User Profile</a></li>
        </div>
        <div class="payout">
            <small>Payout = <span>${{point_sum |floatformat:"3"}}</span></small>
        </div>
        <li><a href="{% url 'accounts:logout_yttasker' %}">Logout</a></li>
        
    </div>
</div>
{% endblock sidebar %}
{% block content %}
<div class="main">
    <div class="sidemenu">
        <li><a href="{% url 'dashboard:dashboard' %}"><i class="bx bx-briefcase"></i>Todays Task</a></li>
        <li><a href="{% url 'dashboard:notification' %}"><i class="bx bx-notification"></i>Notification</a></li>
        <li class="active"><a href="#"><i class="bx bx-user"></i>User Profile</a></li>
        <div class="extra-menu">
            <small><b>{{request.user.email}}</b></small>
            <li><a href="{% url 'accounts:logout_yttasker' %}">Logout</a></li>
        </div>
    </div>
    <div class="main-content">
        <div class="user-form">
            <h3>User Profile</h3>
        <form action="{% url 'dashboard:update_profile' request.user.id %}" method="post">
            {% csrf_token %}
            {% if request.user.is_staff %}
                <label for="username">Username</label>
                <input type="text" placeholder="{{request.user.username}}" name="username" value="{{request.user.username}}">
                <label for="email">Email</label>
                <input type="email" readonly name="email" id="email" placeholder="{{request.user.email}}" value="{{request.user.email}}">
                <label for="momo_number">Momo Number</label>
                <input type="number" name="momo_number" id="" placeholder="None">
                <label for="Password">Password</label>
                <input type="password" readonly name="password" placeholder="**************">
                <label for="phonenumber">Phone Number</label>
                <input type="number" name="phonenumber" placeholder="None" id="">
                <input class="btn" type="submit" placeholder="Update">
            {% else %}
                <label for="username">Username</label>
                <input type="text" placeholder="{{yttasker_profile.username}}" name="username" value="{{yttasker_profile.username}}">
                <label for="email">Email</label>
                <input type="email" readonly name="email" id="email" placeholder="{{yttasker_profile.email}}" value="{{yttasker_profile.email}}">
                <label for="momo_number">Momo Number</label>
                <input type="number" name="momo_number" id="" placeholder="{{yttasker_profile.momo_number}}" value="{{yttasker_profile.momo_number}}"">
                <label for="Password">Password</label>
                <input type="password" readonly name="password" placeholder="*******************" >
                <label for="phonenumber">Phone Number</label>
                <input type="number" name="phonenumber" placeholder="{{yttasker_profile.phonenumber}}" id="" value="{{yttasker_profile.phonenumber}}">
                <input class="btn" placeholder="Update" type="submit" >
            {% endif %}
        </form>
        </div>
    </div>
</div>

<script>
     const content_stretch = document.querySelectorAll("#content_description")
        for(const stretch of content_stretch){
            stretch.addEventListener("click", ()=>{
                if(stretch.classList.contains("stretch")){
                    stretch.innerHTML="Content Description <i class='bx bx-chevron-down'></i>"
                    stretch.classList.remove("stretch");
                }else{
                    stretch.innerHTML="Content Description <i class='bx bx-chevron-up'></i>"
                    stretch.classList.add("stretch");
                }
                
                
                
                const parentDiv = stretch.closest(".description")
                const cardDiv = stretch.closest(".card")
                cardDiv.classList.toggle("expand")
                stretch.classList.toggle("expand")
                const content_paragraph = parentDiv.querySelector("p")
                if(content_paragraph){

                    content_paragraph.classList.toggle("expand")
                }
            })
            
        }

</script>
{% endblock content %}