YTTask_Backend/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("", home, name="landingpage"),
    path("createsuperuser/", create_superuser),
    path("accounts/", include("accounts.urls")),
    path("dashboard/", include("dashboard.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from .views import create_yttasker, login_yttasker, logout_yttasker
app_name = "accounts"
urlpatterns = [
   path('create_yttasker/', create_yttasker, name="create_yttasker"),
   path('login_yttasker/', login_yttasker, name="login_yttasker"),
   path('logout_yttasker/', logout_yttasker, name="logout_yttasker")

]

templates/landingpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&family=Poppins&family=Open+Sans&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/landingpage.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>YTTasks</title>
</head>
<body>
    <nav class="navbar">
        
        <div class="nav-logo">
            <img src="{% static 'images/logo.png' %}" alt="">
            <span>YTTasks.gh</span>
        </div>

        <div class="nav-action">
            <a href="{% url 'accounts:login_yttasker' %}" class="btn">Login</a>
            <a href="{% url 'accounts:create_yttasker' %}" class="btn">SignUp</a>
        </div>
         <!-- Nav-trigger -->
         <div class="nav-trigger" id="nav-trigger">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </nav>
    <!-- Sidebar -->
    <div class="sidebar" id="sidebar">
        <div class="content">
            <li><a href="{% url 'accounts:login_yttasker' %}">Login</a></li>
            <li><a href="{% url 'accounts:create_yttasker' %}">Sign Up</a></li>
        </div>
    </div>
    <div class="landingpage">
        <div class="notification">
            <small>We are hiring. Deadline for signup is 23rd August, 2023</small>
        </div>
        <div class="main-page">
            <div class="left-section">
                <h3>Get paid to market and encode youtube videos</h3>
                <p>Earn up to 350 dollars per month, just encoding youtube links of your favourite youtube videos.</p>
                <a href="{% url 'accounts:login_yttasker' %}" class="btn">Start Earning</a>
            </div>
            <div class="right-section">
                <img src="{% static 'images/Seo.png' %}" alt="">
            </div>
        </div>
    </div>
    <footer class="footer">
        <span>Copyright &copy YTTasks.com, 2023</span>
        <small>YTTasks</small>
    </footer>


    <script>
        const navTrigger = document.getElementById("nav-trigger")
        const sidebar = document.getElementById("sidebar")
        navTrigger.addEventListener("click", ()=>{
            navTrigger.classList.toggle("active")
            sidebar.classList.toggle("active")
        })
    </script>
</body>
</html>